apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-ns
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: {{.Values.port}}
      targetPort: {{.Values.port}}
