apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app-ns
  labels:
    app: app
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: {{.Values.imageName}}
        ports:
        - containerPort: {{.Values.port}}
